name: React CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/commit-front:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/commit-front:latest

          # Stop and remove the existing container if it exists
          docker stop commit-front || true
          docker rm commit-front || true

          # Run the new container
          docker run -d --name commit-front -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/commit-front:latest

          # Restart Nginx to ensure changes are picked up
          sudo systemctl restart nginx
