name: React CI/CD with Docker, EC2, and HTTPS (Existing SSL)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build React App
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/commit-front:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          # Stop existing containers
          sudo docker stop commit-front || true
          sudo docker rm commit-front || true

          # Pull and run the new Docker image
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/commit-front:latest
          sudo docker run -d --name commit-front -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/commit-front:latest

          sudo systemctl restart nginx
